#! /bin/bash

set -euo pipefail

main() {
    if [[ $# == 0 ]]; then
        echo "usage: irtest test.xi..."
    fi

    for f in "$@"; do
        nonce=TEMP
        dname=$(dirname $f)
        fname=$(basename $f)
        noext=$(basename $f .xi)
        pervasive_file="$dname/pervasives.xi"

        # don't do anything for temp files
        if [[ "$fname" != "$nonce"* ]] && [[ "$fname" != "pervasives.xi" ]] ; then
            tempname="$dname/$nonce-$fname"
            tempname_noext="$dname/$(basename $dname/$nonce-$fname .xi)"

            cat "$pervasive_file" "$f" > "$tempname"

            # outputfiles[0]="$dname/$noext.nothing-out"
            # outputfiles[1]="$dname/$noext.astfolded-out"
            outputfiles[0]="$tempname_noext.typed-out"
            outputfiles[1]="$tempname_noext.nothing-out"
            outputfiles[2]="$tempname_noext.ir-cfold-out"
            outputfiles[3]="$tempname_noext.lower-out"
            outputfiles[4]="$tempname_noext.blkreorder-out"

            # TODO: run stuff
            libpath="-libpath $dname"
            # ./xic --typecheck $libpath "$tempname"
            # ./xic --irgen --ast-cfold $libpath "$tempname"
            ./xic --tcdebug $libpath "$tempname"
            # mv "$tempname_noext.typed" "$tempname_noext.typed"

            ./xic --irgen --nothing $libpath "$tempname"
            mv "$tempname_noext.ir" "$tempname_noext.nothing"

            ./xic --irgen --ir-cfold $libpath "$tempname"
            mv "$tempname_noext.ir" "$tempname_noext.ir-cfold"

            ./xic --irgen --lower $libpath "$tempname"
            mv "$tempname_noext.ir" "$tempname_noext.lower"

            ./xic --irgen --blkreorder $libpath "$tempname"
            mv "$tempname_noext.ir" "$tempname_noext.blkreorder"

            ./xi "$tempname_noext.typed" &> "${outputfiles[0]}" || true
            ./ir "$tempname_noext.nothing" &> "${outputfiles[1]}" || true
            ./ir "$tempname_noext.ir-cfold" &> "${outputfiles[2]}" || true
            ./ir "$tempname_noext.lower" &> "${outputfiles[3]}" || true
            ./ir "$tempname_noext.blkreorder" &> "${outputfiles[4]}" || true

            for ((i = 0; i < ${#outputfiles[*]}; i++)); do
                for ((j = i+1; j < ${#outputfiles[*]}; j++)); do
                    filea="${outputfiles[$i]}"
                    fileb="${outputfiles[$j]}"
                    if ! diff "$filea" "$fileb" > /dev/null; then
                        echo "$filea and $fileb" differ
                    fi
                done
            done
        fi
    done
}

main "$@"
