#! /bin/bash

set -euo pipefail

main() {
    if [[ $# == 0 ]]; then
        echo "usage: irtest test.xi..."
    fi

    for f in "$@"; do
        nonce=TEMP
        dname=$(dirname $f)
        fname=$(basename $f)
        pervasive_file="$dname/pervasives.xi"

        # don't do anything for remnant dummy programs
        if [[ "$fname" != "$nonce"* ]]; then
            cat "$pervasive_file" "$f" > "$dname/$nonce-$fname"
            # run stuff
            # diff stuff
        fi
    done
}

main "$@"
